use_frameworks!

platform :ios, '9.0'

target 'TestComponent_Example' do
  pod 'TestComponent', :path => '../'

  target 'TestComponent_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
