#source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Rong12/TestComponentProject.git'
use_frameworks!

platform :ios, '9.0'

target 'TestComponent_Example' do
#  pod 'TestComponent', '0.1.1'
  pod 'TestComponent', :path => '../'

end
